In [ ]:
print("Hello Naba")

# Numpy

* the rank of an array is the munber of dimentions
* the shape of the array is a tuple of integers giving size of the array along each dimention
* A vector is an array with a single dimention (there is no difference btw row and column vectors)
* A matrix refers to an array with two dimention 
* 3-D or heigher (for 3-D or heigher dimentional arrays,the term tensor is also commonly used)
* tensorFlow is a free and open sources software library for machine learning and artificial intelligence 
* Dimention also called axis 

In [1]:
!pip install numpy

In [2]:
import numpy as np

### this is np.linspace numpy function/method example

In [3]:
my_array = np.linspace(0, 10, 6) 
print(my_array)

[ 0.  2.  4.  6.  8. 10.]


In [4]:
my_list=[1,2,3,4]
result=np.array(my_list)
print(result)

[1 2 3 4]


In [6]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
array_sum = np.sum(my_array)
print("Sum of all elements:", array_sum)

Sum of all elements: 21


In [7]:

zeros_array = np.zeros((3, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
my_array = np.arange(0, 10, 2)  

print(my_array)

[0 2 4 6 8]


In [9]:

original_array = np.arange(1, 13)

reshaped_array = np.reshape(original_array, (3, 4))
print(reshaped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

array_sum = np.sum(my_array)

print("Sum of all elements:", array_sum)

Sum of all elements: 21


In [11]:

my_array = np.array([1, 2, 3, 4, 5])

array_mean = np.mean(my_array)

print("Mean of all elements:", array_mean)

Mean of all elements: 3.0


In [12]:
my_array = np.array([10, 30, 20, 50, 40])

max_index = np.argmax(my_array)

print("Index of maximum value:", max_index)

Index of maximum value: 3


# 1-D Array

In [2]:
import numpy as np
food = np.array(["pakory","kheer","samosa"])
food

array(['pakory', 'kheer', 'samosa'], dtype='<U6')

In [3]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
len(price)

3

In [8]:
price[1]

5

In [9]:
price[0:]

array([5, 5, 5])

In [4]:
price.mean()

5.0

In [5]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

# Array Functions

In [11]:
a=np.array([1,2,1.1,3,2.2])
a

array([1. , 2. , 1.1, 3. , 2.2])

In [13]:
a.sort()
a

array([1. , 1.1, 2. , 2.2, 3. ])

In [14]:
b=np.array([11,21,31.1,3,2.2])
b

array([11. , 21. , 31.1,  3. ,  2.2])

In [16]:
c=np.concatenate((a,b))
c

array([ 1. ,  1.1,  2. ,  2.2,  3. , 11. , 21. , 31.1,  3. ,  2.2])

# 2-D Arrays

In [18]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
b=np.array([[11,12,13,14],[25,26,27,28]])
b

array([[11, 12, 13, 14],
       [25, 26, 27, 28]])

In [20]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [25, 26, 27, 28]])

In [25]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [25, 26, 27, 28]])

In [26]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [28]:
# to find number of dimentions 
a.ndim

2

In [30]:
a.size

8

In [31]:
a.shape

(2, 4)

In [34]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c=a.reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
# convert 1-D into 2-D
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [39]:
a.shape

(6,)

In [40]:
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6]])

In [41]:
b.shape

(1, 6)

In [43]:
# coulmn wise 2-D

b=a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
a[2:3]

array([3])

In [45]:
a*6

array([ 6, 12, 18, 24, 30, 36])

In [46]:
a+6

array([ 7,  8,  9, 10, 11, 12])

In [48]:
a.sum()

21

In [49]:
a.mean()

3.5